/* 채점 결과에 대한 각 메시지 구분 맵핑 */
/* 채점 결과에 대한 각 구분 정보 */
const RESULT_CATEGORY = {
    RESULT_PENDING: 'wait',
    RESULT_PENDING_REJUDGE: 'rejudge-wait',
    RESULT_NO_JUDGE: 'no-judge',
    RESULT_PREPARE_FOR_JUDGE: 'compile',
    RESULT_JUDGING: 'judging',
    RESULT_ACCEPTED: 'ac',
    RESULT_PARTIALLY_ACCEPTED: 'pac',
    RESULT_PRESENTATION_ERROR: 'pe',
    RESULT_WRONG_ANSWER: 'wa',
    RESULT_ACCEPTED_NOT_CORRECT: 'awa',
    RESULT_TIME_LIMIT_EXCEEDED: 'tle',
    RESULT_MEMORY_LIMIT_EXCEEDED: 'mle',
    RESULT_OUTPUT_LIMIT_EXCEEDED: 'ole',
    RESULT_RUNTIME_ERROR: 'rte',
    RESULT_COMPILATION_ERROR: 'ce',
    RESULT_UNVAILABLE: 'co',
    RESULT_DELETED: 'del',
  };

// BOJ Levels
const bj_level = {
    0: 'Unrated',
    1: 'Bronze V',
    2: 'Bronze IV',
    3: 'Bronze III',
    4: 'Bronze II',
    5: 'Bronze I',
    6: 'Silver V',
    7: 'Silver IV',
    8: 'Silver III',
    9: 'Silver II',
    10: 'Silver I',
    11: 'Gold V',
    12: 'Gold IV',
    13: 'Gold III',
    14: 'Gold II',
    15: 'Gold I',
    16: 'Platinum V',
    17: 'Platinum IV',
    18: 'Platinum III',
    19: 'Platinum II',
    20: 'Platinum I',
    21: 'Diamond V',
    22: 'Diamond IV',
    23: 'Diamond III',
    24: 'Diamond II',
    25: 'Diamond I',
    26: 'Ruby V',
    27: 'Ruby IV',
    28: 'Ruby III',
    29: 'Ruby II',
    30: 'Ruby I',
    31: 'Master',
};